import React from "react";
import { Nunito } from "next/font/google";

import "./globals.css";

import StyledComponentsRegistry from "../lib/AntdRegistry";
import { ConfigProvider } from "antd";
import { GLOBAL_COLORS } from "../constants/stylesConsts";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body className={nunito.className}>
      <StyledComponentsRegistry>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: GLOBAL_COLORS.primary_dark_purple,
            },
          }}
        >
          {children}
        </ConfigProvider>
      </StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;
